// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djxfaoacwmhsuxhscknt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqeGZhb2Fjd21oc3V4aHNja250Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNzMwOTUsImV4cCI6MjA1Nzk0OTA5NX0.89CrMDVmvmpzwkkovy59rVERtA4Lq0cRCNCohkf7r-g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);